dist:
  name: obsidian-core-collector
  version: 0.1.0
  otelcol_version: 0.96.0
  output_path: ../collector
  go.os: [linux, darwin]
  go.arch: [amd64, arm64]

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.96.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.96.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.96.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/healthcheckextension v0.96.0
