name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Install gosec
      run: |
        go install github.com/securego/gosec/v2/cmd/gosec@latest
    
    - name: Install govulncheck
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Run govulncheck
      run: |
        govulncheck ./...
      
    - name: Run Gosec Security Scanner
      run: |
        gosec -fmt=json -out=results.json ./...
      
    - name: Upload scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.json